sudo: required

install:
    - sudo bash -c "echo deb http://archive.ubuntu.com/ubuntu artful main >> /etc/apt/sources.list"
    - sudo apt-get update
    - sudo apt-get install live-build reprepro busybox -y

script:
    - sudo bash build.sh

after_success:
    - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    - mv halium.rootfs.tar.gz halium-debian-rootfs_$(date +%Y%m%d).tar.gz
    - bash upload.sh halium-debian-rootfs_$(date +%Y%m%d).tar.gz

branches:
  only:
   - buster
   - travis
