sudo: required

services:
  - docker

before_install:
  - docker pull debian:sid-slim

script:
  - docker run -v $PWD:/mnt/rootfs-builder debian:sid-slim /bin/bash -c "apt update; apt install qemu-user-static live-build reprepro busybox -y; cd /mnt/rootfs-builder; bash build.sh"

after_success:
    - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    - mv halium.rootfs.tar.gz halium-debian-rootfs_$(date +%Y%m%d).tar.gz
    - bash upload.sh halium-debian-rootfs_$(date +%Y%m%d).tar.gz

branches:
  only:
   - buster
   - travis
